### ISSUE TITLE
Where is the schematic diagram?

### ISSUE THREAD

**Issue by designingSparks** [weteor/3W6#13]
Is there a schematic diagram of this that you could make available? I couldn't find it in the repo.

**Comment by weteor** [comment]
You mean as PDF's? No I don't  have them in the repo, because I don't really want to have to keep them up to date if something changes.

The schematics and pcbs are done in Kicad though, which is free to use/download. And those files are published in the repo here: https://github.com/weteor/3W6/tree/main/pcb/3w6. I also find them more practical to use then PDFs.

Would this suffice for you? If your really need to have them in some other format, I could add them, I think.

**Comment by designingSparks** [comment]
Yes, that would be sufficient.
