### ISSUE TITLE
[Feature Request] NiceNano Version / Bluetooth

### ISSUE THREAD

**Issue by 10bn** [weteor/3W6#8]
Hi, thanks for sharing this great project with us!

Could you imagine to do a PCB template that has a niceNano or some other integrated Bluetooth module? I personally wouldn't mind to have the halves still connected via a wire as long I could ride of the main cable...

**Comment by weteor** [comment]
it's something I am thinking about, but haven't had the time to do. Nice Nano or other BT Modules are out of the question unfortunately, because they are simply too large. On Board Chip is the way to go, but that is quite a bit of work ... and finding a place for the batterz is challenging too.

tl;dr I have plans, but I don't think it will happen in the next few month
